# Generated by Django 3.0.4 on 2020-04-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('abbreviated_name', models.CharField(max_length=200)),
                ('conducting_body_full_name', models.CharField(max_length=200)),
                ('conducting_body_abbreviated_name', models.CharField(max_length=200)),
                ('official_website', models.CharField(max_length=200)),
                ('tentative_date', models.DateField()),
                ('exam_level', models.CharField(choices=[('NT', 'National'), ('INT', 'International'), ('ST', 'State'), ('DT', 'District')], max_length=5)),
                ('eligibility', models.IntegerField(choices=[(1, 'Matric Pass'), (2, 'HS Pass'), (3, 'Under Graduate'), (4, 'Post Graduate'), (0, 'Other')])),
                ('document', models.FileField(upload_to='exams/documents/')),
                ('about', models.TextField()),
                ('cutoff_details', models.TextField()),
            ],
        ),
    ]
