# Generated by Django 3.0.4 on 2020-06-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('abbreviated_name', models.CharField(max_length=200)),
                ('conducting_body_full_name', models.CharField(max_length=200)),
                ('conducting_body_abbreviated_name', models.CharField(max_length=200)),
                ('official_website', models.CharField(max_length=200)),
                ('tentative_date', models.DateField()),
                ('exam_level', models.CharField(choices=[('NT', 'National'), ('INT', 'International'), ('ST', 'State'), ('DT', 'District')], max_length=5)),
                ('eligibility', models.IntegerField(choices=[(1, 'Metric Pass'), (2, 'HS Pass'), (3, 'Under Graduate'), (4, 'Post Graduate'), (0, 'Other')])),
                ('document', models.FileField(upload_to='exams/documents/')),
                ('about', models.TextField()),
                ('cutoff_details', models.TextField()),
                ('slug', models.SlugField()),
                ('is_top', models.BooleanField(default=False)),
                ('quick_facts', models.TextField(null=True)),
                ('exam_pattern', models.TextField(null=True)),
                ('admit_card', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, null=True)),
                ('primary_date', models.DateField()),
                ('secondary_date', models.DateField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCutoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('G', 'General'), ('SC', 'Schedule Caste'), ('ST', 'Schedule Tribe'), ('OBC', 'Other Backward Class'), ('PWD', 'Pwd'), ('CM', 'Common'), ('OT', 'Other')], max_length=5)),
                ('cutoff_marks_1', models.FloatField(max_length=20)),
                ('cutoff_year_1', models.DateField()),
                ('cutoff_marks_2', models.FloatField(max_length=20, null=True)),
                ('cutoff_year_2', models.DateField(null=True)),
                ('cutoff_marks_3', models.FloatField(max_length=20, null=True)),
                ('cutoff_year_3', models.DateField(null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
            ],
        ),
    ]
