# Generated by Django 3.0.4 on 2020-06-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='meta',
            field=models.TextField(null=True),
        ),
    ]
