# Generated by Django 3.0.4 on 2020-06-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200619_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='abbreviated_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='conducting_body_abbreviated_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='conducting_body_full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='cutoff_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='document',
            field=models.FileField(null=True, upload_to='exams/documents/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='eligibility',
            field=models.IntegerField(choices=[(1, 'Metric Pass'), (2, 'HS Pass'), (3, 'Under Graduate'), (4, 'Post Graduate'), (0, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_level',
            field=models.CharField(choices=[('NT', 'National'), ('INT', 'International'), ('ST', 'State'), ('DT', 'District')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_top',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='official_website',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='tentative_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='examcutoff',
            name='category',
            field=models.CharField(choices=[('G', 'General'), ('SC', 'Schedule Caste'), ('ST', 'Schedule Tribe'), ('OBC', 'Other Backward Class'), ('PWD', 'Pwd'), ('CM', 'Common'), ('OT', 'Other')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='examcutoff',
            name='cutoff_marks_1',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examcutoff',
            name='cutoff_year_1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='examdate',
            name='primary_date',
            field=models.DateField(null=True),
        ),
    ]
