# Generated by Django 3.0.4 on 2020-07-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('lead_type', models.IntegerField(choices=[(0, 'Other'), (1, 'Course'), (3, 'Exam'), (2, 'College')], null=True)),
                ('lead_description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Other'), (1, 'Successful'), (3, 'Contacted'), (2, 'Failed'), (4, 'On Hold'), (5, 'In Progress')], null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='FootPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=200, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermodule.Profile')),
            ],
        ),
    ]
