# Generated by Django 3.0.4 on 2020-06-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('abbreviated_name', models.CharField(max_length=200)),
                ('stream', models.IntegerField(choices=[(1, 'Engineering'), (2, 'Medical'), (3, 'Humanities'), (4, 'Finance'), (5, 'Arts'), (6, 'Science'), (0, 'Other')])),
                ('level', models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('D', 'Diploma'), ('PHD', 'Doctorate'), ('OT', 'Others')], max_length=5)),
                ('duration', models.IntegerField()),
                ('eligibility', models.IntegerField(choices=[(1, 'Matric Pass'), (2, 'HS Pass'), (3, 'Under Graduate'), (4, 'Post Graduate'), (0, 'Other')])),
                ('exam', models.CharField(choices=[('SM', 'Semester'), ('AN', 'Annual'), ('WK', 'Weekly'), ('PT', 'Patent'), ('PP', 'Paper'), ('OT', 'Other')], max_length=3)),
                ('average_course_fee', models.DecimalField(decimal_places=5, max_digits=20)),
                ('about', models.TextField()),
                ('syllabus_csv', models.TextField()),
                ('slug', models.SlugField()),
                ('is_top', models.BooleanField(default=False)),
                ('quick_facts', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Job')),
            ],
        ),
    ]
