# Generated by Django 3.0.4 on 2020-06-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200619_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='range',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='top_companies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus_csv',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coursejob',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='coursejob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Job'),
        ),
        migrations.CreateModel(
            name='FAQLinkCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.FAQCourse')),
            ],
        ),
    ]
