# Generated by Django 3.0.4 on 2020-06-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200619_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abbreviated_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='average_course_fee',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='eligibility',
            field=models.IntegerField(choices=[(1, 'Matric Pass'), (2, 'HS Pass'), (3, 'Under Graduate'), (4, 'Post Graduate'), (0, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam',
            field=models.CharField(choices=[('SM', 'Semester'), ('AN', 'Annual'), ('WK', 'Weekly'), ('PT', 'Patent'), ('PP', 'Paper'), ('OT', 'Other')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_top',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('D', 'Diploma'), ('PHD', 'Doctorate'), ('OT', 'Others')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='stream',
            field=models.IntegerField(choices=[(1, 'Engineering'), (2, 'Medical'), (3, 'Humanities'), (4, 'Finance'), (5, 'Arts'), (6, 'Science'), (0, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='faqcourse',
            name='answers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faqcourse',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
