# Generated by Django 3.0.4 on 2020-07-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200629_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='jobs',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='average_course_fee',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
