# Generated by Django 3.0.4 on 2020-06-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('abbreviated_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('brochure', models.FileField(null=True, upload_to='college/brochure/')),
                ('image', models.ImageField(null=True, upload_to='college/image/')),
                ('logo', models.ImageField(null=True, upload_to='college/logo/')),
                ('ownership', models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'Other')])),
                ('approval', models.CharField(max_length=100, null=True)),
                ('college_type', models.IntegerField(choices=[(0, 'Graduation College'), (1, 'Diploma College'), (2, 'Vocational Training')])),
                ('date_of_establishment', models.DateField(null=True)),
                ('slug', models.SlugField()),
                ('about', models.TextField(null=True)),
                ('is_top', models.BooleanField(default=False)),
                ('quick_facts', models.TextField(null=True)),
                ('admission_process', models.TextField(null=True)),
                ('placements', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('abbreviated_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('degree_type', models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('D', 'Diploma'), ('PHD', 'Doctorate'), ('OT', 'Others')], max_length=3)),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='college.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='StreamCollegeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.College')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Stream')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=40, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.College')),
            ],
        ),
        migrations.CreateModel(
            name='EntranceExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.College')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
            ],
        ),
    ]
