# Generated by Django 3.0.4 on 2020-06-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20200619_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='abbreviated_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_type',
            field=models.IntegerField(choices=[(0, 'Graduation College'), (1, 'Diploma College'), (2, 'Vocational Training')], null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='is_top',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='ownership',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='abbreviated_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officialcontact',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='officialcontact',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='degree_type',
            field=models.CharField(choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('D', 'Diploma'), ('PHD', 'Doctorate'), ('OT', 'Others')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
