# Generated by Django 3.0.4 on 2020-07-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20200629_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='date_of_establishment',
        ),
        migrations.AddField(
            model_name='college',
            name='degrees',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='established_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='streams',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='college/gallery/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.College')),
            ],
        ),
    ]
