# Generated by Django 3.0.4 on 2020-07-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20200701_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='quick_facts',
        ),
    ]
